version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_hw
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  app:
    build: .
    container_name: python_data_app
    depends_on:
      - mongodb
    environment:
      - DB_HOST=ваш_mysql_хост
      - DB_DATABASE=my_ad_data
      - DB_USER=me
      - DB_PASSWORD=artem228
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=ad_engagement_db
      - MONGO_USER=root
      - MONGO_PASSWORD=example

volumes:
  mongo-data: